name: 'Build and push docker image'
description: 'Build the docker image and push it to the registry.'
inputs:
  registry:
    default: 'ghcr.io'
    description: "Docker registry"
  username:
    description: 'Registry username'
    required: true
  password:
    description: 'Registry password'
    required: true
  docker-image:
    description: "Docker image name"
    required: true
  docker-tag:
    description: "Docker image tag"
    required: true

runs:
  using: "composite"
  steps:
    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push container image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ inputs.docker-image }}:${{ inputs.docker-tag }}
