name: 'Build and push docker image'
description: 'Build the docker image and push it to the registry'

inputs:
  username:
    description: "Registry username"
    required: true
  password:
    description: "Registry password"
    required: true
  docker-image:
    description: "Docker image name"
    required: true
  docker-tag:
    description: "Docker image tag"
    required: true
  working-directory:
    description: 'The working directory'
    default: '.'
  dockerfile:
    description: "Path to the Dockerfile. (default {working-directory}/Dockerfile)"
    default: "Dockerfile"
  registry:
    description: "Docker registry"
    default: "ghcr.io"

runs:
  using: "composite"
  steps:
    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push container image
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.working-directory }}
        file: ${{ inputs.dockerfile }}
        push: true
        tags: |
          ${{ inputs.docker-image }}:${{ inputs.docker-tag }}
